### ISSUE TITLE
JRE Version 8 Update 121 HTTPS ssl exception

### ISSUE THREAD

**Issue by josueeduardo** [josueeduardo/rest-client#14]
From [#199](https://github.com/Mashape/unirest-java/issues/199)

Background - there is an existing software which is using unirest to access an https website endpoint. The SSL certificate of the website (endpoint) is issued by GoDaddy.

This software was used for a long time by users without issues - However, using the latest JRE Version 8 Update 121, today one user got this SSL certificate exception. It's the same software and the same website which used to work without issues. Initially I thought it's an issue with the user's java installation so I un-installed java and installed back but I got the same error.

Do you have any idea what is happening and why (suddenly) it started to fail? What are my options?

`com.mashape.unirest.http.exceptions.UnirestException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:143) at com.mashape.unirest.request.BaseRequest.asJson(BaseRequest.java:68)`

**Comment by erayerdin** [comment]
One year late, yet I think it might be related to [this SO answer](https://stackoverflow.com/a/39966770/2926992). I haven't tried it though.
