### ISSUE TITLE
Improved error handling

### ISSUE THREAD

**Issue by josueeduardo** [josueeduardo/rest-client#16]
From [#194](https://github.com/Mashape/unirest-java/issues/194)

Sample code:

   ```
 public static void main(String[] args) throws Exception {
        HttpResponse<JsonNode> response = Unirest.get("http://ajaygautam.com/random.json").asJson();
        System.out.println("Status: " + response.getStatusText());
    }
```
Fails at asJson() with:

/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/...

```
Exception in thread "main" com.mashape.unirest.http.exceptions.UnirestException: java.lang.RuntimeException: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:143)
	at com.mashape.unirest.request.BaseRequest.asJson(BaseRequest.java:68)
	at ScrapUnirestSample.main(ScrapUnirestSample.java:7)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
	at com.mashape.unirest.http.HttpResponse.<init>(HttpResponse.java:106)
	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:139)
	... 7 more
Caused by: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
	at com.mashape.unirest.http.JsonNode.<init>(JsonNode.java:51)
	at com.mashape.unirest.http.HttpResponse.<init>(HttpResponse.java:95)
	... 8 more
Caused by: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
	at org.json.JSONArray.<init>(JSONArray.java:106)
	at org.json.JSONArray.<init>(JSONArray.java:145)
	at com.mashape.unirest.http.JsonNode.<init>(JsonNode.java:48)
	... 9 more

```

**Comment by ks228** [comment]
Did you solve it? I am getting the same in Post.

**Comment by josueeduardo** [comment]
What's the URL you're using ? This happens when the response body is not a valid json.
